from django.urls import path
from . import views

app_name = 'application'

urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('my-profile/', views.student_profile, name='student_profile'),
    path('student-register/', views.user_register, name='user_register'),
    path('enroll-existing-user/', views.enroll_existing_user_general, name='enroll_existing_user_general'),
    path('get-batches/<int:franchise_id>/', views.get_batches, name='get_batches'),
    path('course/', views.course_fee_list, name='course_fee_list'),
    path('fee-reminders/', views.fee_reminders, name='fee_reminders'),
    path('franchises/', views.franchise_list, name='franchise_list'),
    path('franchise/register/', views.franchise_register, name='franchise_register'),
    path('franchise/<int:pk>/edit/', views.franchise_edit, name='franchise_edit'),
    path('franchise/<int:pk>/report/', views.franchise_report, name='franchise_report'),
    path('franchise/<int:pk>/batch/add/', views.batch_create, name='batch_create'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/students/', views.batch_students, name='batch_students'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/student/<int:user_pk>/', views.student_detail, name='student_detail'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/student/<int:user_pk>/edit/', views.edit_student_details, name='edit_student_details'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/register/', views.batch_user_register, name='batch_user_register'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/fee-management/', views.batch_fee_management, name='batch_fee_management'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/student-fee-management/<int:user_pk>/', views.student_fee_management, name='student_fee_management'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/student-fee-management/<int:user_pk>/print-installment-invoice/<int:installment_pk>/', views.print_installment_invoice, name='print_installment_invoice'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/student-fee-management/<int:user_pk>/edit-installment/', views.edit_installment_setup, name='edit_installment_setup'),
    path('franchise/<int:franchise_pk>/batch/<int:batch_pk>/enroll-existing-user/', views.enroll_existing_user, name='enroll_existing_user'),
    path('inactive-users/', views.inactive_users, name='inactive_users'),
    path('receipt/', views.receipt_search, name='receipt_search'),
    path('receipt_detail/<int:franchise_id>/', views.receipt_detail, name='receipt_detail'),
    path('receipt_detail/<int:franchise_id>/clear-session/', views.clear_payment_session, name='clear_payment_session'),
    path('receipt/<int:franchise_id>/print/', views.print_receipt_detail, name='print_receipt_detail'),
    path('receipt/<int:franchise_id>/print-payment/', views.print_payment_detail, name='print_payment_detail'),
    path("get-course-fee/<path:course_id>/", views.get_course_fee, name="get_course_fee"),
    path("receipt/api/search/", views.receipt_search_api, name="receipt_search_api"),
    path('fee-report/', views.fee_report, name='fee_report'),
    path('franchise_fees_report/', views.franchise_fees_report, name='franchise_fees_report'),
    path('monthly_fees_report/', views.monthly_fees_report, name='monthly_fees_report'),
    path('combined-fees-report/', views.combined_fees_report, name='combined_fees_report'),
    path('special-access-register/', views.special_access_register, name='special_access_register'),
    path('special-access-user/<int:user_id>/edit/', views.edit_special_access_user, name='edit_special_access_user'),
    path('get-batches-for-franchises/', views.get_batches_for_franchises, name='get_batches_for_franchises'),
    path('get-batch-franchise/<int:batch_id>/', views.get_batch_franchise, name='get_batch_franchise'),  
    path('student-counts/', views.student_counts, name='student_counts'),
    path('special-dashboard/', views.special_user_dashboard, name='special_user_dashboard'),
    path('roles/', views.roles, name='roles'),
    path('roles/<int:group_id>/edit/', views.edit_role, name='edit_role'),
    path('roles/<int:group_id>/delete/', views.delete_role, name='delete_role'),
]