# Generated by Django 4.2.20 on 2025-10-31 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='course_overviews.courseoverview')),
            ],
        ),
        migrations.CreateModel(
            name='BatchFeeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('repayment_period_days', models.PositiveIntegerField(default=30)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_management', to='application.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordinator', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('repayment_period_days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.batch')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.franchise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'franchise', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch_fee_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.batchfeemanagement')),
                ('user_franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_management', to='application.userfranchise')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAccessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('all', 'All Permissions'), ('franchise_management', 'Franchise Management'), ('fee_management', 'Fee Management'), ('student_management', 'Student Management'), ('reporting', 'Reporting')], default='all', max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_batches', models.ManyToManyField(blank=True, related_name='special_access_users', to='application.batch')),
                ('allowed_franchises', models.ManyToManyField(blank=True, related_name='special_access_users', to='application.franchise')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_dashboard', 'Can view dashboard'), ('view_reports', 'Can view reports'), ('view_profile', 'Can view profile'), ('manage_roles', 'Can manage roles'), ('manage_users', 'Can manage users'), ('process_payment', 'Can process payments')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='application.installment')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_period_days', models.PositiveIntegerField()),
                ('batch_fee_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_templates', to='application.batchfeemanagement')),
            ],
        ),
        migrations.AddField(
            model_name='installment',
            name='student_fee_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='application.studentfeemanagement'),
        ),
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='course_overviews.courseoverview')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='application.franchise'),
        ),
    ]
